export const GET_COUNTRY_DATA_LOAD="GET_COUNTRY_DATA_LOAD";
export const GET_REQUEST_COUNTRY_DATA="GET_REQUEST_COUNTRY_DATA";
export const COUNTRY_CLEAR_DATA="COUNTRY_CLEAR_DATA";
export const ERROR_REQUEST_DATA="ERROR_REQUEST_DATA";